import serial
import wave
import struct
import sys
import os
import re
import time

script_dir = os.path.dirname(os.path.abspath(__file__))

# Serial configuration
PORT = 'COM4'
# PORT = '/dev/ttyUSB0'
BAUD_RATE = 2000000
SAMPLE_RATE = 16000 
OUTPUT_FILENAME = os.path.join(script_dir, "audio.wav")

try:
    ser = serial.Serial(PORT, BAUD_RATE)
    ser.reset_input_buffer() 
except Exception as e:
    print(f"Error! Port {PORT} is busy or not found.")
    sys.exit()

print("Listening... Speak into the microphone!")
print("Press Ctrl+C to stop and save the .wav file.")
recorded_samples = []

# Regex to remove ANSI color codes generated by ESP_LOG
ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')

# Stores data fragments between bulk reads
remainder = b'' 

try:
    while True:
        # Check if there is data waiting in the USB buffer
        if ser.in_waiting > 0:
            # Read the entire block at once (Bulk Read)
            raw_data = ser.read(ser.in_waiting)
            
            # Combine the remainder of the previous read with the new data
            full_data = remainder + raw_data
            
            # Split the data using the newline character
            lines = full_data.split(b'\n')
            
            # The last element might be incomplete, keep it for the next cycle
            remainder = lines.pop()
            
            for line in lines:
                # Decode and strip the line safely
                text_line = line.decode('utf-8', errors='ignore').strip()
                
                if not text_line:
                    continue

                # Remove ANSI colors from ESP_LOG
                clean_text = ansi_escape.sub('', text_line)

                # Split by ':' to separate the ESP_LOG tag from the actual value
                parts = clean_text.split(':')

                if len(parts) > 0:
                    try:
                        # Extract the number, remove spaces, and convert to integer
                        raw_number = parts[-1].strip()
                        val = int(raw_number) + 3300
                        recorded_samples.append(val)
                    except ValueError:
                        # Ignore invalid conversions
                        pass
        else:
            # Small pause to prevent 100% CPU usage
            time.sleep(0.005)

except KeyboardInterrupt:
    print(f"\nClosing and processing {len(recorded_samples)} samples...")
    ser.close()
    
    # WAV export logic
    print(f"Saving audio to '{OUTPUT_FILENAME}'...")
    
    with wave.open(OUTPUT_FILENAME, 'w') as wav_file:
        wav_file.setnchannels(1) # Mono
        wav_file.setsampwidth(2) # 2 bytes per sample
        wav_file.setframerate(SAMPLE_RATE)
        
        for sample in recorded_samples:
            # 16-bit WAV requires values strictly between -32768 and 32767
            clamped_sample = int(max(-32768, min(32767, sample)))
            
            # Pack as little-endian short
            byte_data = struct.pack('<h', clamped_sample)
            wav_file.writeframesraw(byte_data)
            
    print("Done! Go listen to your file.")